version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - food-network

  auth-service:
    build:
      context: ./backend/services/auth-service
    ports:
      - "3000:3000"
    networks:
      - food-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=your-secret-key

  restaurant-service:
    build: ./backend/services/restaurant
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - food-network

  order-service:
    build: ./backend/services/order
    ports:
      - "3002:3000"
    depends_on:
      - mongodb
    networks:
      - food-network

  delivery-service:
    build: ./backend/services/delivery-service
    ports:
      - "3003:3000"
    depends_on:
      - mongodb
    networks:
      - food-network

  api-gateway:
    image: nginx:alpine
    ports:
      - "5000:80"               # Expose Nginx on port 5000
    volumes:
      - ./backend/api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - restaurant-service
      - order-service
      - delivery-service
    networks:
      - food-network

  frontend:
    build: ./frontend
    ports:
      - "8085:80"
    networks:
      - food-network

networks:
  food-network:
    driver: bridge
